### ISSUE TITLE
Hahsing script failing

### ISSUE THREAD

**Issue by BournSupremacy** [odomlab2/sci-rocket#26]
Hi Job,

I've run into a problem with the hashing parts of the pipeline and as far as I can tell, I don't think it's because of my files. Initially, I ran the pipeline and it failed in the `workflow/rules/scripts/demultiplexing/sciClasses.py` script with this error:

```
  1 2024-01-15 13:32:51 - (sci-rocket) INFO: Starting sample-based demultiplexing of Olat.MA1.2_Nova_run2:
  2 (R1) Olat.MA1.2_Nova_run2/raw_reads_split/R1_2-of-10.fastq.gz
  3 (R2) Olat.MA1.2_Nova_run2/raw_reads_split/R2_2-of-10.fastq.gz
  4 2024-01-15 13:32:52 - (sci-rocket) INFO: Hashing sample(s) detected in this experiment, hashing subroutines are enabled for these samples. After counting, hash-reads are discarded.
  5 Jess, it read the dict_hashing part
  6 Traceback (most recent call last):
  7   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/sciClasses.py", line 422, in determine_hash
  8     name_hash = dict_hashing[self.sample_name]["sheet"][sequence_hash_raw]
  9                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
 10 KeyError: 'GTTATTTAGC'
 11 
 12 During handling of the above exception, another exception occurred:
 13 
 14 Traceback (most recent call last):
 15   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/demux_rocket.py", line 628, in <module>
 16     main(sys.argv[1:])
 17   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/demux_rocket.py", line 624, in main
 18     sciseq_sample_demultiplexing(log=log, experiment_name=args.experiment_name, samples=samples, barcodes=barcodes, path_r1=args.r1, path_r2=args.r2, path_out=args.out)
 19   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/demux_rocket.py", line 456, in sciseq_sample_demultiplexing
 20     x.determine_hash(dict_hashing)
 21   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/sciClasses.py", line 429, in determine_hash
 22     if name_hash != None:
 23        ^^^^^^^^^
 24 UnboundLocalError: cannot access local variable 'name_hash' where it is not associated with a value
```

I figured out that the script was finding what it thought were hashes (so 10 nt sequence, as shown in line 10) but these are not hashes in my hash sheet, so the `name_hash` variable was not getting set. So I added in the `name_hash = None` line to the script before the variable is set in line 421. This then got past this error when I reran, but then I ran into another error, now in the `workflow/rules/scripts/demultiplexing/demux_rocket.py` script: 

```
  1 2024-01-15 13:39:07 - (sci-rocket) INFO: Starting sample-based demultiplexing of Olat.MA1.2_Nova_run2:
  2 (R1) Olat.MA1.2_Nova_run2/raw_reads_split/R1_2-of-10.fastq.gz
  3 (R2) Olat.MA1.2_Nova_run2/raw_reads_split/R2_2-of-10.fastq.gz
  4 2024-01-15 13:39:07 - (sci-rocket) INFO: Hashing sample(s) detected in this experiment, hashing subroutines are enabled for these samples. After counting, hash-reads are discarded.
  5 Jess, it read the dict_hashing part
  6 Traceback (most recent call last):
  7   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/demux_rocket.py", line 628, in <module>
  8     main(sys.argv[1:])
  9   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/demux_rocket.py", line 624, in main
 10     sciseq_sample_demultiplexing(log=log, experiment_name=args.experiment_name, samples=samples, barcodes=barcodes, path_r1=args.r1, path_r2=args.r2, path_out=args.out)
 11   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/demux_rocket.py", line 499, in sciseq_sample_demultiplexing
 12     qc = update_qc(qc, x)
 13          ^^^^^^^^^^^^^^^^
 14   File "/g/dorrity/bin/sci-rocket/workflow/rules/scripts/demultiplexing/demux_rocket.py", line 241, in update_qc
 15     if x.cellular_barcode not in qc["hashing"][x.sample_name]["counts"][x.hashing_name]:
 16                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
 17 KeyError: 'counts'
```

Unfortunately, I'm out of my depth to try and fix this one. I know from my testing (see line 5 above and others that I very unprofessionally checked) that the qc["hashing"][hashing_sample] variable is being set, but then for some reason the update part of the script is failing, and the error seems to say it's got to do with the `counts` variable. Like I said, I'm totally out of my depth here, but if you might have an idea of what is going on, I would be very grateful to hear it! Especially if you think it might be something wrong with my setup or hashing files.

Best,
Jess

**Comment by J0bbie** [comment]
Hi Jess,

I just updated the hashing logic a few days ago, incl. this error: https://github.com/odomlab2/sci-rocket/commit/38a7229f1caf33ca8444498b392fc8a77e496a19

Could you check if you have the latest code (`git status` / `git pull`)?
It might be that this bug is already fixed.

Best,

Job
